# Generated by Django 5.0.1 on 2024-02-06 12:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=100)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(default='I Semester', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('cgpa', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='^(A|A-|B\\+|B|B-|C\\+|C|D|F)$')])),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.course')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.semester')),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.student')),
            ],
        ),
    ]
