# Generated by Django 5.0.1 on 2024-02-07 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('roll_number', 'course_code', 'sem_id')},
        ),
        migrations.CreateModel(
            name='SGPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('roll_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.student')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.semester')),
            ],
        ),
    ]
