# Generated by Django 5.0.1 on 2024-02-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_enrollment_unique_together_sgpa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sgpa',
            unique_together={('roll_number', 'sem_id')},
        ),
    ]
